version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "main"
    commit-message:
      prefix: "chore"
      include: "scope"
    labels:
      - "dependencies"
    ignore:
      # next major versions need to be updated manually
      - dependency-name: "next"
        update-types: ["version-update:semver-major"]
      - dependency-name: "react"
        update-types: ["version-update:semver-major"]
      - dependency-name: "react-dom"
        update-types: ["version-update:semver-major"]
      - dependency-name: "tailwindcss"
        update-types: ["version-update:semver-major"]
    groups:
      # Group all patch and minor updates for dev dependencies
      dev-dependencies:
        dependency-type: "development"
        update-types:
          - "patch"
          - "minor"
      # Group all patch and minor updates for production dependencies
      prod-dependencies:
        dependency-type: "production"
        update-types:
          - "patch"
          - "minor"